### ISSUE TITLE
Request code

### ISSUE THREAD

**Issue by hch-baobei** [Xiyue-Wang/1st-in-MICCAI-MIDOG-2021-challenge#1]
Hello, I am working on a project in this direction recently, I wonder when your code will be published, so THAT I can learn from the outstanding people while I admire the code.

**Comment by Xiyue-Wang** [comment]
Thank you very much for your attention. We are preparing to expand our article. Now it is almost half completed. It is expected to take another month. After we submit the article, it will be made public.

**Comment by hch-baobei** [comment]
Thank you very much for your reply, and I look forward to reading your articles and works. Happy New Year!

**Comment by hch-baobei** [comment]
Good morning. May I ask how long it will take to see your masterpiece?

**Comment by Xiyue-Wang** [comment]
Thank you very much for your continued attention, almost 90% of the work is done.Please understand researchers are taking multiple works to do.I will let you know once it's done.I'm guessing no more than 2 months

**Comment by hch-baobei** [comment]
Thank you. I'm really sorry for not receiving your reply in time. I look forward to your completed works, which I believe will definitely open my eyes.

**Comment by Geeks-Sid** [comment]
Any updates on this?

**Comment by Xiyue-Wang** [comment]
Will keep updating, you know, now that China is open, we are all going through Covid-19, I will upload the data and weights this week

**Comment by hch-baobei** [comment]
Come on, I will close this issue. I hope you get well soon. I'm all right.

**Comment by Geeks-Sid** [comment]
Hope you are doing well, any updates on the files?
